source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.7.0"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem "rails", "~> 6.0.3", ">= 6.0.3.2"
# Use postgresql as the database for Active Record
gem "pg", ">= 0.18", "< 2.0"
# Use Puma as the app server
gem "puma", "~> 4.1"
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem "jbuilder", "~> 2.7"
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
gem "bcrypt", "~> 3.1.7"

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.4.2", require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  # Adds support for Capybara system testing and selenium driver
  gem "annotate", "~> 3.1", ">= 3.1.1"
  gem "capybara", "~> 3.33"
  gem "factory_bot_rails", "~> 6.0"
  gem "guard", "~> 2.16", ">= 2.16.2"
  gem "guard-rspec", "~> 4.7", ">= 4.7.3"
  gem "rspec-rails", "~> 4.0", ">= 4.0.1"
  gem "selenium-webdriver", "~> 3.142", ">= 3.142.7"
  gem "webmock", "~> 3.8", ">= 3.8.3"
  gem "faker", "~> 2.13"
  # pry
  gem "pry", "~> 0.12", ">= 0.12.2"
  gem "pry-byebug", "~> 3.4"
  gem "pry-rails", "~> 0.3", ">= 0.3.9"
  gem "pry-doc", "~> 1.0"
  gem "standard", "~> 0.4.7"
  gem "spring-commands-rspec", "~> 1.0", ">= 1.0.4"
end

group :development do
  gem "listen", "~> 3.2"
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"

  # Code completion/snippets
  gem "solargraph"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
